import {Movie, MovieCast} from '../shared/types'

export const movies : Movie[] = [
  {
    adult: false,
    backdrop_path: '/sRLC052ieEzkQs9dEtPMfFxYkej.jpg',
    genre_ids: [ 878 ],
    id: 848326,
    original_language: 'en',
    original_title: 'Rebel Moon - Part One: A Child of Fire',
    overview: 'When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.',
    popularity: 2136.3,
    poster_path: '/6epeijccmJlnfvFitfGyfT7njav.jpg',
    release_date: '2023-12-15',
    title: 'Rebel Moon - Part One: A Child of Fire',
    video: false,
    vote_average: 6.4,
    vote_count: 750
  },
  {
    adult: false,
    backdrop_path: '/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg',
    genre_ids: [ 28, 12, 14 ],
    id: 572802,
    original_language: 'en',
    original_title: 'Aquaman and the Lost Kingdom',
    overview: "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
    popularity: 1605.303,
    poster_path: '/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg',
    release_date: '2023-12-20',
    title: 'Aquaman and the Lost Kingdom',
    video: false,
    vote_average: 6.5,
    vote_count: 299
  },
  {
    adult: false,
    backdrop_path: '/15Fe18IglCCP1jJoj5F529on0IA.jpg',
    genre_ids: [ 28, 35 ],
    id: 1029575,
    original_language: 'en',
    original_title: 'The Family Plan',
    overview: "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
    popularity: 954.371,
    poster_path: '/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
    release_date: '2023-12-14',
    title: 'The Family Plan',
    video: false,
    vote_average: 7.3,
    vote_count: 457
  },

  {
    adult: false,
    backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    genre_ids: [ 18, 36 ],
    id: 872585,
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 746.349,
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    release_date: '2023-07-19',
    title: 'Oppenheimer',
    video: false,
    vote_average: 8.1,
    vote_count: 5713
  },
  {
    adult: false,
    backdrop_path: '/1jITxVJhkiFJuQuj8NcPLmDNtJg.jpg',
    genre_ids: [ 18, 35, 53 ],
    id: 1234,
    original_language: 'en',
    original_title: 'Saltburn',
    overview: "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton, who invites him to Saltburn, his eccentric family's sprawling estate, for a summer never to be forgotten.",
    popularity: 658.86,
    poster_path: '/qjhahNLSZ705B5JP92YMEYPocPz.jpg',
    release_date: '2023-11-16',
    title: 'Saltburn',
    video: false,
    vote_average: 7.1,
    vote_count: 473
  },
  {
    adult: false,
    backdrop_path: '/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
    genre_ids: [ 80, 18, 36 ],
    id: 466420,
    original_language: 'en',
    original_title: 'Killers of the Flower Moon',
    overview: 'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.',
    popularity: 612.671,
    poster_path: '/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg',
    release_date: '2023-10-18',
    title: 'Killers of the Flower Moon',
    video: false,
    vote_average: 7.5,
    vote_count: 1647
  },
  {
    adult: false,
    backdrop_path: '/ktHEdqmMWC1wdfPRMRCTZe2OISL.jpg',
    genre_ids: [ 27, 9648, 53 ],
    id: 1071215,
    original_language: 'en',
    original_title: 'Thanksgiving',
    overview: 'After a Black Friday riot ends in tragedy, a mysterious Thanksgiving-inspired killer terrorizes Plymouth, Massachusetts - the birthplace of the holiday. Picking off residents one by one, what begins as random revenge killings are soon revealed to be part of a larger, sinister holiday plan.',
    popularity: 606.566,
    poster_path: '/f5f3TEVst1nHHyqgn7Z3tlwnBIH.jpg',
    release_date: '2023-11-16',
    title: 'Thanksgiving',
    video: false,
    vote_average: 6.7,
    vote_count: 347
  },
  {
    adult: false,
    backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
    genre_ids: [ 16, 10751, 10402, 14, 35 ],
    id: 901362,
    original_language: 'en',
    original_title: 'Trolls Band Together',
    overview: "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
    popularity: 563.374,
    poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
    release_date: '2023-10-12',
    title: 'Trolls Band Together',
    video: false,
    vote_average: 7.2,
    vote_count: 436
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    genre_ids: [ 28, 80, 53 ],
    id: 385687,
    original_language: 'en',
    original_title: 'Fast X',
    overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 537.344,
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    release_date: '2023-05-17',
    title: 'Fast X',
    video: false,
    vote_average: 7.2,
    vote_count: 4566
  },
  {
    adult: false,
    backdrop_path: '/hRPKfuotMeyRiXXGPKmmrVXD5DG.jpg',
    genre_ids: [ 28 ],
    id: 504148,
    original_language: 'en',
    original_title: 'The Serpent',
    overview: "Top special agent Lucinda Kavsky works for a secret part of the CIA. She's given a special assignment but then set up by her own agency.",
    popularity: 530.362,
    poster_path: '/AvMoan3rxCDZpNf59BmAP2G8q5x.jpg',
    release_date: '2021-01-28',
    title: 'The Serpent',
    video: false,
    vote_average: 3.8,
    vote_count: 12
  },
  {
    adult: false,
    backdrop_path: '/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg',
    genre_ids: [ 28, 12, 878 ],
    id: 670292,
    original_language: 'en',
    original_title: 'The Creator',
    overview: 'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
    popularity: 519.619,
    poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
    release_date: '2023-09-27',
    title: 'The Creator',
    video: false,
    vote_average: 7.2,
    vote_count: 1645
  },
  {
    adult: false,
    backdrop_path: '/X8yF6STUk5Zr5nAuLBJiio8Sxh.jpg',
    genre_ids: [ 18, 10749 ],
    id: 1143183,
    original_language: 'tl',
    original_title: 'Rewind',
    overview: "Mary (Marian Rivera) loves John (Dingdong Dantes) for as long as she can remember. But after years of marriage, John's priorities shift, leading to a strained relationship with Mary, which causes a tragic accident that takes away Mary's life. Until one day, John gets an extraordinary proposition - to rewind time and save the life of the woman he loves.",
    popularity: 506.227,
    poster_path: '/vW80VheMJhHsj0pDVYJL3qAMWMd.jpg',
    release_date: '2023-12-25',
    title: 'Rewind',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/4mmrgZW9bcgMRFdV1lCcXqCEXEr.jpg',
    genre_ids: [ 28, 18, 12, 9648, 53 ],
    id: 755401,
    original_language: 'en',
    original_title: 'Skydog',
    overview: 'After a high school senior working on his pilot’s license rescues a dog named Oreo, he finds out his mom is a CIA agent who’s been captured. He teams up with Oreo and a new friend to find his mother and uncover double agents inside the CIA.',
    popularity: 504.779,
    poster_path: '/5M3bY1rl9QIQSmrAGPEt9qutj64.jpg',
    release_date: '2020-10-20',
    title: 'Skydog',
    video: false,
    vote_average: 7.3,
    vote_count: 8
  },
];

export const movieCasts: MovieCast[] = [
  {
    movieId: 1234,
    actorName: "Joe Bloggs",
    roleName: "Male Character 1",
    roleDescription: "description of character 1",
  },
  {
    movieId: 1234,
    actorName: "Alice Broggs",
    roleName: "Female Character 1",
    roleDescription: "description of character 2",
  },
  {
    movieId: 2345,
    actorName: "Joe Bloggs",
    roleName: "Male Character 1",
    roleDescription: "description of character 3",
  },
  {
    movieId: 848326,
    actorName: "Alice Broggs",
    roleName: "Female Character 1",
    roleDescription: "description of character 2",
  },
  {
    movieId: 848326,
    actorName: "Joe Cloggs",
    roleName: "Male Character 2",
    roleDescription: "description of character 3",
  },
  {
    movieId: 848326,
    actorName: "Joe Shmogs",
    roleName: "Male Character 3",
    roleDescription: "description of character 3",
  },
];







